-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'MFA_SETUP';
ALTER TYPE "AuditAction" ADD VALUE 'MFA_ENABLED';
ALTER TYPE "AuditAction" ADD VALUE 'MFA_VERIFIED';
ALTER TYPE "AuditAction" ADD VALUE 'MFA_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'MFA_DISABLED';
ALTER TYPE "AuditAction" ADD VALUE 'MFA_RECOVERY_USED';

-- AlterTable
ALTER TABLE "mfa_devices" ADD COLUMN "recovery_codes" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "last_used_at" TIMESTAMP(3);
